<?php
class Realtime_sync_model extends MY_Model {

  function __construct() {
      ///Call the Model constructor
      parent::__construct();
  }

  function sync_data_to_bigquery($queue_data = array()) 
  {

        if (STOP_BIGQUERY_REALTIME_QUEUE == '0') {
            include_once 'aws-php-sdk/aws-autoloader.php';
            $this->load->library('Sqs');
            $sqs_object = new Sqs();
            $results = array();
            //Pt to overview rporting table sync in bigquery
            if (isset($queue_data['pass_no']) && !empty($queue_data['pass_no']) && ($queue_data['action'] == 'deactivate_visitor_pass' || (!empty($queue_data['channel_type']) && $queue_data['channel_type'] == '5'))) {
                $results = $this->secondarydb->db->query('SELECT * FROM prepaid_tickets pt1 WHERE passNo="' . $queue_data['pass_no'] . '" and version = (select max(version) from prepaid_tickets pt2 where pt2.prepaid_ticket_id = pt1.prepaid_ticket_id and pt1.passNo="' . $queue_data['pass_no'] . '")')->result();
            } else if (isset($queue_data['vgn_list']) && !empty($queue_data['vgn_list'])) {
                $results = $this->secondarydb->db->query('select * from prepaid_tickets pt1 where visitor_group_no in (' . implode(',', $queue_data['vgn_list']) . ') and version = (select max(version) from prepaid_tickets pt2 where pt2.prepaid_ticket_id = pt1.prepaid_ticket_id and pt1.visitor_group_no in (' . implode(',', $queue_data['vgn_list']) . '))')->result();
            } else if (isset($queue_data['pt_ids_for_BG']) && !empty($queue_data['pt_ids_for_BG'])) {
                $results = $this->secondarydb->db->query('select * from prepaid_tickets pt1 where pt1.prepaid_ticket_id in (' . implode(',', $queue_data['pt_ids_for_BG']) . ') and pt1.version = (select max(version) from prepaid_tickets pt2 where pt1.prepaid_ticket_id= pt2.prepaid_ticket_id and pt1.prepaid_ticket_id in (' . implode(',', $queue_data['pt_ids_for_BG']) . '))')->result();
            } else if (isset($queue_data['visitor_group_no']) && !empty($queue_data['visitor_group_no'])) {
                $results = $this->secondarydb->db->query('select * from prepaid_tickets pt1 where pt1.visitor_group_no ="' . $queue_data['visitor_group_no'] . '"  and pt1.version = (select max(version) from prepaid_tickets pt2 where pt1.prepaid_ticket_id = pt2.prepaid_ticket_id and pt1.visitor_group_no ="' . $queue_data['visitor_group_no'] . '" )')->result();
            }
            $aws_message2 = base64_encode(gzcompress(json_encode($results)));
            $MessageIdss = $sqs_object->sendMessage(LIVE_SCAN_REPORT_QUEUE_URL, $aws_message2);
            if ($MessageIdss != false) {
                $this->load->library('Sns');
                $sns_object = new Sns();
                $err = $sns_object->publish($MessageIdss, LIVE_SCAN_REPORT_QUEUE_URL_ARN);

                /* Select data and sync on BQ */
                $this->order_process_model->getVtDataToSyncOnBQ($queue_data['visitor_group_no']);
            }
            //Pt to overview rporting table sync in bigquery end here

            /* Select data and sync on BQ for VT */
            if (!empty($queue_data['vgn_list'])) {
                $this->getVtDataToSyncOnBQ($queue_data['vgn_list']);
            } else if (!empty($queue_data['pt_ids_for_BG'])) {
                $vgns = array_filter(array_unique(array_column($results, 'visitor_group_no')));
                $this->getVtDataToSyncOnBQ($vgns);
            } else if ($queue_data['visitor_group_no']) {
                $this->getVtDataToSyncOnBQ($queue_data['visitor_group_no']);
            }
            /* Select data and sync on BQ for VT */

            if (!isset($queue_data['vgn_list']) && !isset($queue_data['dont_update_vt'])) {
                $final_visitor_data_to_insert_big_query_transaction_specific = array();
                /*                 * code for bigquery aggvt day table */
                if (isset($queue_data['pass_no']) && !empty($queue_data['pass_no']) && ($queue_data['action'] == 'deactivate_visitor_pass' || (!empty($queue_data['channel_type']) && $queue_data['channel_type'] == '5'))) {
                    /* Get data on the basis of passNo if channel_type='5' */
                    $final_visitor_data_to_insert_big_query_transaction_specific = $this->secondarydb->db->query('SELECT activation_method,time_based_done,id,is_prioticket,targetlocation,card_name,created_date,tp_payment_method,order_confirm_date,transaction_id,visitor_invoice_id,invoice_id,channel_id,channel_name,reseller_id,reseller_name,saledesk_id,partner_category_id,partner_category_name,saledesk_name,financial_id,financial_name,ticketId,invoice_type,ticket_title,ticketwithdifferentpricing,ticketpriceschedule_id,hto_id,visitor_group_no,vt_group_no,visit_date_time,partner_id,partner_name,is_custom_setting,museum_name,museum_id,hotel_name,primary_host_name,hotel_id,is_refunded,shift_id,pos_point_id,pos_point_name,passNo,pass_type,ticketAmt,visit_date,ticketType,tickettype_name,paid,payment_method,isBillToHotel,pspReference,card_type,ticketPrice,captured,age_group,discount,is_block,isDiscountInPercent,debitor,creditor,total_gross_commission,total_net_commission,partner_gross_price,partner_gross_price_without_combi_discount,partner_net_price,order_currency_partner_gross_price,order_currency_partner_net_price,partner_net_price_without_combi_discount,isCommissionInPercent,tax_id,tax_value,extra_discount,distributor_partner_id,distributor_partner_name,payment_date,tax_name,timezone,adyen_status,invoice_status,row_type,merchant_admin_id,market_merchant_id,updated_by_id,updated_by_username,voucher_updated_by,voucher_updated_by_name,redeem_method,cashier_id,cashier_name,roomNo,nights,user_name,user_age,gender,user_image,visitor_country,merchantAccountCode,merchantReference,original_pspReference,targetcity,paymentMethodType,service_name,distributor_status,transaction_type_name,shopperReference,issuer_country_code,selected_date,booking_selected_date,from_time,to_time,slot_type,ticket_status,booking_status,channel_type,ticket_booking_id,without_elo_reference_no,extra_text_field_answer,is_voucher,group_type_ticket,group_price,group_quantity,group_linked_with,supplier_currency_code,supplier_currency_symbol,order_currency_code,order_currency_symbol,currency_rate,col7,col8,is_shop_product,used,issuer_country_name,distributor_type,commission_type,scanned_pass,groupTransactionId,is_prepaid,account_number,chart_number,supplier_gross_price,supplier_discount,supplier_ticket_amt,supplier_tax_value,supplier_net_price,action_performed,updated_at,col2 FROM visitor_tickets vt1 WHERE passNo = "' . $queue_data['pass_no'] . '" and version = (select max(version) from visitor_tickets vt2 where vt2.id = vt1.id and vt1.passNo = "' . $queue_data['pass_no'] . '") ')->result_array();
                } else if (isset($queue_data['pt_ids_with_ticket_for_VT_BG']) && !empty($queue_data['pt_ids_with_ticket_for_VT_BG'])) {
                    foreach ($queue_data['pt_ids_with_ticket_for_VT_BG'] as $main_transaction_id => $sub_ticket_id) {
                        $final_visitor_data_to_insert_big_query_transaction_specific = $this->secondarydb->db->query('select activation_method,time_based_done,id,is_prioticket,targetlocation,card_name,created_date,tp_payment_method,order_confirm_date,transaction_id,visitor_invoice_id,invoice_id,channel_id,channel_name,reseller_id,reseller_name,saledesk_id,partner_category_id,partner_category_name,saledesk_name,financial_id,financial_name,ticketId,invoice_type,ticket_title,ticketwithdifferentpricing,ticketpriceschedule_id,hto_id,visitor_group_no,vt_group_no,visit_date_time,partner_id,partner_name,is_custom_setting,museum_name,museum_id,hotel_name,primary_host_name,hotel_id,is_refunded,shift_id,pos_point_id,pos_point_name,passNo,pass_type,ticketAmt,visit_date,ticketType,tickettype_name,paid,payment_method,isBillToHotel,pspReference,card_type,ticketPrice,captured,age_group,discount,is_block,isDiscountInPercent,debitor,creditor,total_gross_commission,total_net_commission,partner_gross_price,partner_gross_price_without_combi_discount,partner_net_price,order_currency_partner_gross_price,order_currency_partner_net_price,partner_net_price_without_combi_discount,isCommissionInPercent,tax_id,tax_value,extra_discount,distributor_partner_id,distributor_partner_name,payment_date,tax_name,timezone,adyen_status,invoice_status,row_type,merchant_admin_id,order_updated_cashier_id,order_updated_cashier_name,market_merchant_id,updated_by_id,updated_by_username,voucher_updated_by,voucher_updated_by_name,redeem_method,cashier_id,cashier_name,roomNo,nights,user_name,user_age,gender,user_image,visitor_country,merchantAccountCode,merchantReference,original_pspReference,targetcity,paymentMethodType,service_name,distributor_status,transaction_type_name,shopperReference,issuer_country_code,selected_date,booking_selected_date,from_time,to_time,slot_type,ticket_status,booking_status,channel_type,ticket_booking_id,without_elo_reference_no,extra_text_field_answer,is_voucher,group_type_ticket,group_price,group_quantity,group_linked_with,supplier_currency_code,supplier_currency_symbol,order_currency_code,order_currency_symbol,currency_rate,col7,col8,is_shop_product,used,issuer_country_name,distributor_type,commission_type,scanned_pass,groupTransactionId,is_prepaid,account_number,chart_number,supplier_gross_price,supplier_discount,supplier_ticket_amt,supplier_tax_value,supplier_net_price,action_performed,updated_at,col2 from visitor_tickets vt1 where transaction_id = "' . $main_transaction_id . '" and ticketId = "' . $sub_ticket_id . '" and version=(select max(version) from visitor_tickets vt2 where vt2.id=vt1.id and v1.transaction_id = "' . $main_transaction_id . '" and vt1.ticketId = "' . $sub_ticket_id . '")')->result_array();
                    }
                } else if (isset($queue_data['pt_ids_for_VT_BG']) && !empty($queue_data['pt_ids_for_VT_BG'])) {
                    $final_visitor_data_to_insert_big_query_transaction_specific = $this->secondarydb->db->query('select activation_method,time_based_done,id,is_prioticket,targetlocation,card_name,created_date,tp_payment_method,order_confirm_date,transaction_id,visitor_invoice_id,invoice_id,channel_id,channel_name,reseller_id,reseller_name,saledesk_id,partner_category_id,partner_category_name,saledesk_name,financial_id,financial_name,ticketId,invoice_type,ticket_title,ticketwithdifferentpricing,ticketpriceschedule_id,hto_id,visitor_group_no,vt_group_no,visit_date_time,partner_id,partner_name,is_custom_setting,museum_name,museum_id,hotel_name,primary_host_name,hotel_id,is_refunded,shift_id,pos_point_id,pos_point_name,passNo,pass_type,ticketAmt,visit_date,ticketType,tickettype_name,paid,payment_method,isBillToHotel,pspReference,card_type,ticketPrice,captured,age_group,discount,is_block,isDiscountInPercent,debitor,creditor,total_gross_commission,total_net_commission,partner_gross_price,partner_gross_price_without_combi_discount,partner_net_price,order_currency_partner_gross_price,order_currency_partner_net_price,partner_net_price_without_combi_discount,isCommissionInPercent,tax_id,tax_value,extra_discount,distributor_partner_id,distributor_partner_name,payment_date,tax_name,timezone,adyen_status,invoice_status,row_type,merchant_admin_id,order_updated_cashier_id,order_updated_cashier_name,market_merchant_id,updated_by_id,updated_by_username,voucher_updated_by,voucher_updated_by_name,redeem_method,cashier_id,cashier_name,roomNo,nights,user_name,user_age,gender,user_image,visitor_country,merchantAccountCode,merchantReference,original_pspReference,targetcity,paymentMethodType,service_name,distributor_status,transaction_type_name,shopperReference,issuer_country_code,selected_date,booking_selected_date,from_time,to_time,slot_type,ticket_status,booking_status,channel_type,ticket_booking_id,without_elo_reference_no,extra_text_field_answer,is_voucher,group_type_ticket,group_price,group_quantity,group_linked_with,supplier_currency_code,supplier_currency_symbol,order_currency_code,order_currency_symbol,currency_rate,col7,col8,is_shop_product,used,issuer_country_name,distributor_type,commission_type,scanned_pass,groupTransactionId,is_prepaid,account_number,chart_number,supplier_gross_price,supplier_discount,supplier_ticket_amt,supplier_tax_value,supplier_net_price,action_performed,updated_at,col2 from visitor_tickets vt1 where transaction_id in (' . implode(',', $queue_data['pt_ids_for_VT_BG']) . ') and version = (select max(version) from visitor_tickets vt2 where vt2.id = vt1.id and vt1.transaction_id in (' . implode(',', $queue_data['pt_ids_for_VT_BG']) . '))')->result_array();
                } else if (isset($queue_data['visitor_group_no']) && !empty($queue_data['visitor_group_no'])){
                    $final_visitor_data_to_insert_big_query_transaction_specific = $this->secondarydb->db->query('select activation_method,time_based_done,id,is_prioticket,targetlocation,card_name,created_date,tp_payment_method,order_confirm_date,transaction_id,visitor_invoice_id,invoice_id,channel_id,channel_name,reseller_id,reseller_name,saledesk_id,partner_category_id,partner_category_name,saledesk_name,financial_id,financial_name,ticketId,invoice_type,ticket_title,ticketwithdifferentpricing,ticketpriceschedule_id,hto_id,visitor_group_no,vt_group_no,visit_date_time,partner_id,partner_name,is_custom_setting,museum_name,museum_id,hotel_name,primary_host_name,hotel_id,is_refunded,shift_id,pos_point_id,pos_point_name,passNo,pass_type,ticketAmt,visit_date,ticketType,tickettype_name,paid,payment_method,isBillToHotel,pspReference,card_type,ticketPrice,captured,age_group,discount,is_block,isDiscountInPercent,debitor,creditor,total_gross_commission,total_net_commission,partner_gross_price,partner_gross_price_without_combi_discount,partner_net_price,order_currency_partner_gross_price,order_currency_partner_net_price,partner_net_price_without_combi_discount,isCommissionInPercent,tax_id,tax_value,extra_discount,distributor_partner_id,distributor_partner_name,payment_date,tax_name,timezone,adyen_status,invoice_status,row_type,merchant_admin_id,order_updated_cashier_id,order_updated_cashier_name,market_merchant_id,updated_by_id,updated_by_username,voucher_updated_by,voucher_updated_by_name,redeem_method,cashier_id,cashier_name,roomNo,nights,user_name,user_age,gender,user_image,visitor_country,merchantAccountCode,merchantReference,original_pspReference,targetcity,paymentMethodType,service_name,distributor_status,transaction_type_name,shopperReference,issuer_country_code,selected_date,booking_selected_date,from_time,to_time,slot_type,ticket_status,booking_status,channel_type,ticket_booking_id,without_elo_reference_no,extra_text_field_answer,is_voucher,group_type_ticket,group_price,group_quantity,group_linked_with,supplier_currency_code,supplier_currency_symbol,order_currency_code,order_currency_symbol,currency_rate,col7,col8,is_shop_product,used,issuer_country_name,distributor_type,commission_type,scanned_pass,groupTransactionId,is_prepaid,account_number,chart_number,supplier_gross_price,supplier_discount,supplier_ticket_amt,supplier_tax_value,supplier_net_price,action_performed,updated_at,col2 from visitor_tickets vt1 where vt_group_no ="' . $queue_data['visitor_group_no'] . '" and version = (select max(version) from visitor_tickets vt2 where vt2.id = vt1.id and vt1.vt_group_no ="' . $queue_data['visitor_group_no'] . '") ')->result_array();
                }
                $final_visitor_data_to_insert_big_query_compressed = base64_encode(gzcompress(json_encode($final_visitor_data_to_insert_big_query_transaction_specific)));
                if (SERVER_ENVIRONMENT == 'Local') {
                    local_queue($final_visitor_data_to_insert_big_query_compressed, 'BIQ_QUERY_AGG_VT_INSERT');
                } else {
                    $MessageId = $sqs_object->sendMessage(AGG_VT_INSERT_QUEUEURL, $final_visitor_data_to_insert_big_query_compressed);
                    if ($MessageId != false) {
                        $err = $sns_object->publish(AGG_VT_INSERT_QUEUEURL, AGG_VT_INSERT_ARN);
                    }
                }
                /*                 * code for aggvt day table end here */
            }
        }
    }
}
?>